### ISSUE TITLE
Consider renaming to awesome lightweights

### ISSUE THREAD

**Issue by tarsius** [jchampemont/awesome-implementations#1]
A large, fully featured, and maybe authoritative *implementation* may also be "awesome". So I would like to encourage you to rename this list to emphasize what it is about: awesome *lightweight* implementations.

Two possible names come to mind: (1) `awesome-lightweight-implementations` and (2) `awesome-lightweights`, which is a bit less precise, but also cooler (like the word "awesome", which also isn't very precise and was likely chosen for the coolness factor).

Cheers!

**Comment by jchampemont** [comment]
Yes I agree (2) is cooler!

Repository renamed :)
